### ISSUE TITLE
 [SUGGESTION] GitHub Project + GitHub Organization

### ISSUE THREAD

**Issue by lezetho** [Cyteon/potatobot#21]
@Cyteon would be great if you could make a GitHub project and assign the people who's working on v3-js (only reason I'm asking this is I cannot access Discord in school and I sorta forgot what im doing 😭 )

**Comment by Cyteon** [comment]
ok

**Comment by lezetho** [comment]
oh and also a github organization just so its easier idfk

**Comment by Cyteon** [comment]
https://github.com/users/Cyteon/projects/1/views/1

**Comment by Cyteon** [comment]
i prob did it wrong

**Comment by Cyteon** [comment]
1 sec

**Comment by lezetho** [comment]
u did lmfao xd

**Comment by lezetho** [comment]
make it public

**Comment by Cyteon** [comment]
10sec

**Comment by lezetho** [comment]
bet

**Comment by Cyteon** [comment]
https://github.com/users/Cyteon/projects/2/views/1

**Comment by lezetho** [comment]
yeah i can see it now

**Comment by lezetho** [comment]
give me edit access fr

**Comment by lezetho** [comment]
GAWD DAMN 19 THINGS????????????????????

**Comment by Cyteon** [comment]
yeah

**Comment by lezetho** [comment]
> yeah

u should give me edit access :3

**Comment by Cyteon** [comment]
Done

**Comment by lezetho** [comment]
w

**Comment by Cyteon** [comment]
Fix stuff ig

**Comment by lezetho** [comment]
bet

**Comment by lezetho** [comment]
done :D

**Comment by lezetho** [comment]
done.
